import { MainLayout } from '@components/common/main-layout';

export default function Home(): JSX.Element {
  return (
    <MainLayout
      title='Next.js Template'
      description='Generated by create next app.'
    >
      <h1>Hello World</h1>
    </MainLayout>
  );
}
